import type { AssetManifest } from "@hushline/shared";

export const assetManifest: AssetManifest = {
  backgrounds: [
    {
      id: "messenger-blank",
      name: "메신저 화면",
      url: "/assets/backgrounds/messenger-blank.svg",
      kind: "messenger",
    },
    {
      id: "school-exterior",
      name: "벚꽃과 학교",
      url: "/assets/backgrounds/school-exterior.png",
      kind: "school",
    },
    {
      id: "school-hallway",
      name: "학교 복도",
      url: "/assets/backgrounds/school-hallway.png",
      kind: "interior",
    },
    {
      id: "school-classroom",
      name: "새 학기 교실",
      url: "/assets/backgrounds/school-classroom.png",
      kind: "interior",
    },
    {
      id: "convenience-store-dawn",
      name: "편의점 앞 새벽",
      url: "/assets/backgrounds/convenience-store-dawn.png?v=bg-20260531",
      kind: "exterior",
      tags: ["global", "convenience-store", "dawn", "street"],
    },
    {
      id: "convenience-store-midnight",
      name: "편의점 앞 자정",
      url: "/assets/backgrounds/convenience-store-midnight.png?v=bg-20260531",
      kind: "exterior",
      tags: ["global", "convenience-store", "midnight", "street"],
    },
    {
      id: "convenience-store-morning",
      name: "편의점 앞 아침",
      url: "/assets/backgrounds/convenience-store-morning.png?v=bg-20260531",
      kind: "exterior",
      tags: ["global", "convenience-store", "morning", "street"],
    },
    {
      id: "sharehouse-living-room",
      name: "셰어하우스 거실",
      url: "/assets/backgrounds/sharehouse-living-room.png?v=bg-20260531",
      kind: "interior",
      tags: ["scenario:shared-house-romance", "sharehouse", "living-room", "morning"],
    },
    {
      id: "sharehouse-living-room-morning",
      name: "셰어하우스 거실 아침",
      url: "/assets/backgrounds/sharehouse-living-room-morning.png?v=bg-20260531",
      kind: "interior",
      tags: ["scenario:shared-house-romance", "sharehouse", "living-room", "morning"],
    },
    {
      id: "sharehouse-living-room-noon",
      name: "셰어하우스 거실 한낮",
      url: "/assets/backgrounds/sharehouse-living-room-noon.png?v=bg-20260531",
      kind: "interior",
      tags: ["scenario:shared-house-romance", "sharehouse", "living-room", "noon"],
    },
    {
      id: "sharehouse-living-room-sunset",
      name: "셰어하우스 거실 일몰",
      url: "/assets/backgrounds/sharehouse-living-room-sunset.png?v=bg-20260531",
      kind: "interior",
      tags: ["scenario:shared-house-romance", "sharehouse", "living-room", "sunset"],
    },
    {
      id: "sharehouse-living-room-night",
      name: "셰어하우스 거실 밤",
      url: "/assets/backgrounds/sharehouse-living-room-night.png?v=bg-20260531",
      kind: "interior",
      tags: ["scenario:shared-house-romance", "sharehouse", "living-room", "night"],
    },
    {
      id: "sharehouse-kitchen",
      name: "셰어하우스 부엌",
      url: "/assets/backgrounds/sharehouse-kitchen.png?v=bg-20260531",
      kind: "interior",
      tags: ["scenario:shared-house-romance", "sharehouse", "kitchen", "morning"],
    },
    {
      id: "sharehouse-kitchen-morning",
      name: "셰어하우스 부엌 아침",
      url: "/assets/backgrounds/sharehouse-kitchen-morning.png?v=bg-20260531",
      kind: "interior",
      tags: ["scenario:shared-house-romance", "sharehouse", "kitchen", "morning"],
    },
    {
      id: "sharehouse-kitchen-day",
      name: "셰어하우스 부엌 낮",
      url: "/assets/backgrounds/sharehouse-kitchen-day.png?v=bg-20260531",
      kind: "interior",
      tags: ["scenario:shared-house-romance", "sharehouse", "kitchen", "day"],
    },
    {
      id: "sharehouse-kitchen-evening",
      name: "셰어하우스 부엌 저녁",
      url: "/assets/backgrounds/sharehouse-kitchen-evening.png?v=bg-20260531",
      kind: "interior",
      tags: ["scenario:shared-house-romance", "sharehouse", "kitchen", "evening"],
    },
    {
      id: "sharehouse-kitchen-night",
      name: "셰어하우스 부엌 밤",
      url: "/assets/backgrounds/sharehouse-kitchen-night.png?v=bg-20260531",
      kind: "interior",
      tags: ["scenario:shared-house-romance", "sharehouse", "kitchen", "night"],
    },
    {
      id: "sharehouse-rooftop",
      name: "셰어하우스 옥상",
      url: "/assets/backgrounds/sharehouse-rooftop.png?v=bg-20260531",
      kind: "exterior",
      tags: ["scenario:shared-house-romance", "sharehouse", "rooftop", "night"],
    },
    {
      id: "sharehouse-rooftop-morning",
      name: "셰어하우스 옥상 아침",
      url: "/assets/backgrounds/sharehouse-rooftop-morning.png?v=bg-20260531",
      kind: "exterior",
      tags: ["scenario:shared-house-romance", "sharehouse", "rooftop", "morning"],
    },
    {
      id: "sharehouse-rooftop-evening",
      name: "셰어하우스 옥상 저녁",
      url: "/assets/backgrounds/sharehouse-rooftop-evening.png?v=bg-20260531",
      kind: "exterior",
      tags: ["scenario:shared-house-romance", "sharehouse", "rooftop", "evening"],
    },
    {
      id: "sharehouse-rooftop-dawn",
      name: "셰어하우스 옥상 새벽",
      url: "/assets/backgrounds/sharehouse-rooftop-dawn.png?v=bg-20260531",
      kind: "exterior",
      tags: ["scenario:shared-house-romance", "sharehouse", "rooftop", "dawn"],
    },
    {
      id: "sharehouse-rooftop-night",
      name: "셰어하우스 옥상 밤",
      url: "/assets/backgrounds/sharehouse-rooftop-night.png?v=bg-20260531",
      kind: "exterior",
      tags: ["scenario:shared-house-romance", "sharehouse", "rooftop", "night"],
    },
    {
      id: "lodge-maintenance-room",
      name: "산장 설비실",
      url: "/assets/backgrounds/lodge-maintenance-room.png",
      kind: "interior",
      tags: ["lodge", "maintenance", "generator", "boiler", "keys", "snow-window"],
    },
    {
      id: "lodge-study-door",
      name: "2층 서재 문 앞",
      url: "/assets/backgrounds/lodge-study-door.png",
      kind: "interior",
      tags: ["lodge", "study-door", "locked-door", "hallway", "book"],
    },
    {
      id: "lodge-upstairs-hallway",
      name: "2층 복도",
      url: "/assets/backgrounds/lodge-upstairs-hallway.png",
      kind: "interior",
      tags: ["lodge", "hallway", "second-floor", "snow-window", "night"],
    },
    {
      id: "lodge-dining-room",
      name: "산장 식당",
      url: "/assets/backgrounds/lodge-dining-room.png",
      kind: "interior",
      tags: ["lodge", "dining-room", "fireplace", "table", "night"],
    },
    {
      id: "lodge-exterior-storm",
      name: "폭설 속 산장 외부",
      url: "/assets/backgrounds/lodge-exterior-storm.png",
      kind: "exterior",
      tags: ["lodge", "exterior", "snowstorm", "night", "isolated"],
    },
    {
      id: "lodge-foyer",
      name: "산장 현관홀",
      url: "/assets/backgrounds/lodge-foyer.png",
      kind: "interior",
      tags: ["lodge", "foyer", "entrance", "staircase", "snow"],
    },
    {
      id: "lodge-exterior-drive",
      name: "눈 쌓인 진입로",
      url: "/assets/backgrounds/lodge-exterior-drive.png",
      kind: "exterior",
      tags: ["lodge", "exterior", "driveway", "snow-tracks", "night"],
    },
    {
      id: "lodge-study-crime-scene",
      name: "서재 사건 현장",
      url: "/assets/backgrounds/lodge-study-crime-scene.png",
      kind: "interior",
      tags: ["lodge", "study", "crime-scene", "body", "blood", "locked-room"],
    },
  ],
  sprites: [
    {
      id: "kang-mujin-neutral",
      characterId: "kang-mujin",
      expression: "neutral",
      url: "/assets/sprites/kang-mujin/full_neutral.png?v=transparent-20260528",
      fullBody: true,
    },
    {
      id: "yoon-haeon-neutral",
      characterId: "yoon-haeon",
      expression: "neutral",
      url: "/assets/sprites/yoon-haeon/full_neutral.png?v=transparent-20260528",
      fullBody: true,
    },
    {
      id: "yoon-seha-neutral",
      characterId: "yoon-seha",
      expression: "neutral",
      url: "/assets/sprites/yoon-seha/full_neutral.png?v=transparent-20260528",
      fullBody: true,
    },
    {
      id: "seo-yujin-neutral",
      characterId: "seo-yujin",
      expression: "neutral",
      url: "/assets/sprites/seo-yujin/full_neutral.png?v=romance-20260531",
      fullBody: true,
    },
    {
      id: "kang-minjae-neutral",
      characterId: "kang-minjae",
      expression: "neutral",
      url: "/assets/sprites/kang-minjae/full_neutral.png?v=romance-20260531",
      fullBody: true,
    },
    {
      id: "han-doyun-neutral",
      characterId: "han-doyun",
      expression: "neutral",
      url: "/assets/sprites/han-doyun/full_neutral.png?v=romance-20260531",
      fullBody: true,
    },
  ],
};
